### PR TITLE
Cards

### PR DESCRIPTION
**Pull request by ark2002**
- Added card component
 - Moved material-icons css link into main.css

### CODE REVIEW

**Review by syed-shaida-hussain — APPROVED** [review]
Looks good , no changes needed but you could have changed the templates instead of setting visibility to hidden. Not changing the templates was only for practice i guess.

**Review by akash-1318 — COMMENTED** [review]
Looks good to merge your HTML code is really clean .

**Comment by ark2002** [comment]
> Looks good , no changes needed but you could have changed the templates instead of setting visibility to hidden. Not changing the templates was only for practice i guess.

yeah i thought we have to keep it that way for components aswell

**Comment by syed-shaida-hussain** [comment]
No need to cahnge it now. It is good.

**Pull request merged**
